### ISSUE TITLE
Crash - java.lang.IllegalArgumentException: illegal object in getInstance: com.braintree.org.bouncycastle.asn1.DERSequence

### ISSUE THREAD

**Issue by quentin41500** [braintree/braintree_android_encryption#8]
Hello, Im currently trying to integrate this SDK and I'm facing a crash. Any idea why?

```
 java.lang.IllegalArgumentException: illegal object in getInstance: com.braintree.org.bouncycastle.asn1.DERSequence
                                                                            at com.braintree.org.bouncycastle.asn1.DERInteger.getInstance(DERInteger.java:26)
                                                                            at com.braintree.org.bouncycastle.asn1.x509.RSAPublicKeyStructure.<init>(RSAPublicKeyStructure.java:62)
                                                                            at com.braintree.org.bouncycastle.asn1.x509.RSAPublicKeyStructure.getInstance(RSAPublicKeyStructure.java:37)
                                                                            at com.braintreegateway.encryption.Rsa.publicKey(Rsa.java:53)
                                                                            at com.braintreegateway.encryption.Rsa.encrypt(Rsa.java:29)
                                                                            at com.braintreegateway.encryption.Braintree.encrypt(Braintree.java:18)
                                                                            at com.test.MainActivity.encryptFormField(MainActivity.kt:32)
                                                                            at com.test.MainActivity.encrypt(MainActivity.kt:22)
                                                                            at com.test.MainActivity.access$encrypt(MainActivity.kt:10)
                                                                            at com.test.MainActivity$onCreate$1.onClick(MainActivity.kt:17)
                                                                            at android.view.View.performClick(View.java:6256)
                                                                            at android.view.View$PerformClick.run(View.java:24697)
                                                                            at android.os.Handler.handleCallback(Handler.java:789)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                            at android.os.Looper.loop(Looper.java:164)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

My sample code is this one:
```
class MainActivity : AppCompatActivity() {
  val MY_KEY = "..."

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    setContentView(R.layout.activity_main)

    button.setOnClickListener({ encrypt() })

  }

  private fun encrypt() {
    val cc = encryptFormField("4111111111111111")
    Log.e("MainActivity", cc)

    val cvv = encryptFormField("123")
    Log.e("MainActivity", cvv)
  }

  private fun encryptFormField(value: String): String {
    val braintree = Braintree(MY_KEY)
    try {
      return braintree.encrypt(value)
    } catch (e: BraintreeEncryptionException) {
      throw RuntimeException("Encryption failed: " + e.message)
    }
  }
}
```

**Comment by crookedneighbor** [comment]
Is there a reason you need to use Client Side Encryption (CSE) to integrate with Braintree? This is a pretty old integration pattern, and we recommend using v2 of the Android SDK instead: https://developers.braintreepayments.com/start/hello-client/android/v2

**Comment by quentin41500** [comment]
Thank you very much for the quick reply.

Sadly yes, I have to use this pattern as the decision is out of my control. The server integration of payment is pretty old and only works with that type of encryption, and this SDK seems to be the only way I can encrypt following the same pattern. 

I know it's not the recommended way and I understand it might be painful, but without this, I have no options to integrate payment at the moment which is a very high priority as you might think, so I would really appreciate any help.

Let me know if I can provide any information to facilitate fixing this issue. I suspect an issue with the key but the key seems correct so not sure about what could be causing it.

**Comment by quentin41500** [comment]
Hello @crookedneighbor,

After some research, I came to the conclusion that the format of my public key is not compatible with the SDK. I noticed that in your unit test, you have a fake public key and after switching it to mine, the test fails.

Would be possible to handle my key format (not sure how to provide you my format without giving you the entire string)?

For information, my team is currently using the JS SDK 1.3.10 and the iOS SDK 2.3.0, and my key is working properly on their end, but when they tried to use the key from the unit test, the JS and iOS SDK gave an error mentioning that the format wasn't correct. 

Hopefully, we can sort this out. I would really appreciate any help on this as it is currently my only solution. Thanks in advance.

**Comment by crookedneighbor** [comment]
I assume the issue is in how the RSA file is attempting to consume your key. https://github.com/braintree/braintree_android_encryption/blob/master/BraintreeAndroidEncryption/src/main/java/com/braintreegateway/encryption/Rsa.java#L25-L45

Would you like to open a Pull Request?

**Comment by crookedneighbor** [comment]
Since we haven't heard from you, I'm going to close this issue. 

This is a deprecated integration type, so it is not on our roadmap to work on. That said, if you open a PR, we're happy to review it, merge and release if the change is sensible.

**Comment by mnchiu** [comment]
@crookedneighbor  and @quentin41500  was there any resolution on this?  Currently we are running into the same issue as @quentin41500 .

**Comment by quentin41500** [comment]
@mnchiu We did not find a solution. I ended up using the javascript SDK through a webview. NOT IDEAL....
